name = "IAISystemImages"
uuid = "413e7391-273a-4866-9cc4-88de0be5f1b8"
authors = ["Interpretable AI <info@interpretable.ai>"]
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SystemImageLoader = "dc30da40-fce8-4b3c-960e-234cbed6f4a5"
